/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AccountDisabledRouteImport } from './routes/account-disabled'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as WaitingApprovalRouteImport } from './routes/waiting-approval'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthEventsRouteImport } from './routes/_auth/events'
import { Route as AuthMahasiswaRouteImport } from './routes/_auth/mahasiswa'
import { Route as AuthMembersRouteImport } from './routes/_auth/members'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthScanRouteImport } from './routes/_auth/scan'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthAttendanceHistoryRouteImport } from './routes/_auth/attendance/history'
import { Route as AuthEventsIdRouteImport } from './routes/_auth/events/$id'
import { Route as AuthEventsNewRouteImport } from './routes/_auth/events/new'
import { Route as ApiAttendanceCheckInRouteImport } from './routes/api/attendance/check-in'
import { Route as ApiEventsIdRouteImport } from './routes/api/events/$id'
import { Route as ApiMembersIdRouteImport } from './routes/api/members/$id'
import { Route as ApiMembersImportRouteImport } from './routes/api/members/import'
import { Route as ApiMembersManualRouteImport } from './routes/api/members/manual'
import { Route as AuthEventsIdQrRouteImport } from './routes/_auth/events/$id/qr'
import { Route as ApiEventsIdSessionRouteImport } from './routes/api/events/$id/session'
import { Route as ApiEventsIdSessionCloseRouteImport } from './routes/api/events/$id/session/close'
import { Route as ApiEventsIdSessionOpenRouteImport } from './routes/api/events/$id/session/open'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDisabledRoute = AccountDisabledRouteImport.update({
  id: '/account-disabled',
  path: '/account-disabled',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingApprovalRoute = WaitingApprovalRouteImport.update({
  id: '/waiting-approval',
  path: '/waiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventsRoute = AuthEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMahasiswaRoute = AuthMahasiswaRouteImport.update({
  id: '/mahasiswa',
  path: '/mahasiswa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMembersRoute = AuthMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthScanRoute = AuthScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthRoute,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAttendanceHistoryRoute = AuthAttendanceHistoryRouteImport.update({
  id: '/attendance/history',
  path: '/attendance/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventsIdRoute = AuthEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthEventsRoute,
} as any)
const AuthEventsNewRoute = AuthEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthEventsRoute,
} as any)
const ApiAttendanceCheckInRoute = ApiAttendanceCheckInRouteImport.update({
  id: '/api/attendance/check-in',
  path: '/api/attendance/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiMembersIdRoute = ApiMembersIdRouteImport.update({
  id: '/api/members/$id',
  path: '/api/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersImportRoute = ApiMembersImportRouteImport.update({
  id: '/api/members/import',
  path: '/api/members/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersManualRoute = ApiMembersManualRouteImport.update({
  id: '/api/members/manual',
  path: '/api/members/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEventsIdQrRoute = AuthEventsIdQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthEventsIdRoute,
} as any)
const ApiEventsIdSessionRoute = ApiEventsIdSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => ApiEventsIdRoute,
} as any)
const ApiEventsIdSessionCloseRoute = ApiEventsIdSessionCloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => ApiEventsIdSessionRoute,
} as any)
const ApiEventsIdSessionOpenRoute = ApiEventsIdSessionOpenRouteImport.update({
  id: '/open',
  path: '/open',
  getParentRoute: () => ApiEventsIdSessionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-disabled': typeof AccountDisabledRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/dashboard': typeof AuthDashboardRoute
  '/events': typeof AuthEventsRouteWithChildren
  '/mahasiswa': typeof AuthMahasiswaRoute
  '/members': typeof AuthMembersRoute
  '/profile': typeof AuthProfileRoute
  '/scan': typeof AuthScanRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/attendance/history': typeof AuthAttendanceHistoryRoute
  '/events/$id': typeof AuthEventsIdRouteWithChildren
  '/events/new': typeof AuthEventsNewRoute
  '/api/attendance/check-in': typeof ApiAttendanceCheckInRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/members/$id': typeof ApiMembersIdRoute
  '/api/members/import': typeof ApiMembersImportRoute
  '/api/members/manual': typeof ApiMembersManualRoute
  '/events/$id/qr': typeof AuthEventsIdQrRoute
  '/api/events/$id/session': typeof ApiEventsIdSessionRouteWithChildren
  '/api/events/$id/session/close': typeof ApiEventsIdSessionCloseRoute
  '/api/events/$id/session/open': typeof ApiEventsIdSessionOpenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-disabled': typeof AccountDisabledRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/dashboard': typeof AuthDashboardRoute
  '/events': typeof AuthEventsRouteWithChildren
  '/mahasiswa': typeof AuthMahasiswaRoute
  '/members': typeof AuthMembersRoute
  '/profile': typeof AuthProfileRoute
  '/scan': typeof AuthScanRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/attendance/history': typeof AuthAttendanceHistoryRoute
  '/events/$id': typeof AuthEventsIdRouteWithChildren
  '/events/new': typeof AuthEventsNewRoute
  '/api/attendance/check-in': typeof ApiAttendanceCheckInRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/members/$id': typeof ApiMembersIdRoute
  '/api/members/import': typeof ApiMembersImportRoute
  '/api/members/manual': typeof ApiMembersManualRoute
  '/events/$id/qr': typeof AuthEventsIdQrRoute
  '/api/events/$id/session': typeof ApiEventsIdSessionRouteWithChildren
  '/api/events/$id/session/close': typeof ApiEventsIdSessionCloseRoute
  '/api/events/$id/session/open': typeof ApiEventsIdSessionOpenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/account-disabled': typeof AccountDisabledRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/login': typeof LoginRoute
  '/waiting-approval': typeof WaitingApprovalRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/events': typeof AuthEventsRouteWithChildren
  '/_auth/mahasiswa': typeof AuthMahasiswaRoute
  '/_auth/members': typeof AuthMembersRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/scan': typeof AuthScanRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/profile': typeof ApiProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/attendance/history': typeof AuthAttendanceHistoryRoute
  '/_auth/events/$id': typeof AuthEventsIdRouteWithChildren
  '/_auth/events/new': typeof AuthEventsNewRoute
  '/api/attendance/check-in': typeof ApiAttendanceCheckInRoute
  '/api/events/$id': typeof ApiEventsIdRouteWithChildren
  '/api/members/$id': typeof ApiMembersIdRoute
  '/api/members/import': typeof ApiMembersImportRoute
  '/api/members/manual': typeof ApiMembersManualRoute
  '/_auth/events/$id/qr': typeof AuthEventsIdQrRoute
  '/api/events/$id/session': typeof ApiEventsIdSessionRouteWithChildren
  '/api/events/$id/session/close': typeof ApiEventsIdSessionCloseRoute
  '/api/events/$id/session/open': typeof ApiEventsIdSessionOpenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-disabled'
    | '/complete-profile'
    | '/login'
    | '/waiting-approval'
    | '/dashboard'
    | '/events'
    | '/mahasiswa'
    | '/members'
    | '/profile'
    | '/scan'
    | '/api/events'
    | '/api/health'
    | '/api/profile'
    | '/auth/callback'
    | '/attendance/history'
    | '/events/$id'
    | '/events/new'
    | '/api/attendance/check-in'
    | '/api/events/$id'
    | '/api/members/$id'
    | '/api/members/import'
    | '/api/members/manual'
    | '/events/$id/qr'
    | '/api/events/$id/session'
    | '/api/events/$id/session/close'
    | '/api/events/$id/session/open'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-disabled'
    | '/complete-profile'
    | '/login'
    | '/waiting-approval'
    | '/dashboard'
    | '/events'
    | '/mahasiswa'
    | '/members'
    | '/profile'
    | '/scan'
    | '/api/events'
    | '/api/health'
    | '/api/profile'
    | '/auth/callback'
    | '/attendance/history'
    | '/events/$id'
    | '/events/new'
    | '/api/attendance/check-in'
    | '/api/events/$id'
    | '/api/members/$id'
    | '/api/members/import'
    | '/api/members/manual'
    | '/events/$id/qr'
    | '/api/events/$id/session'
    | '/api/events/$id/session/close'
    | '/api/events/$id/session/open'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/account-disabled'
    | '/complete-profile'
    | '/login'
    | '/waiting-approval'
    | '/_auth/dashboard'
    | '/_auth/events'
    | '/_auth/mahasiswa'
    | '/_auth/members'
    | '/_auth/profile'
    | '/_auth/scan'
    | '/api/events'
    | '/api/health'
    | '/api/profile'
    | '/auth/callback'
    | '/_auth/attendance/history'
    | '/_auth/events/$id'
    | '/_auth/events/new'
    | '/api/attendance/check-in'
    | '/api/events/$id'
    | '/api/members/$id'
    | '/api/members/import'
    | '/api/members/manual'
    | '/_auth/events/$id/qr'
    | '/api/events/$id/session'
    | '/api/events/$id/session/close'
    | '/api/events/$id/session/open'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AccountDisabledRoute: typeof AccountDisabledRoute
  CompleteProfileRoute: typeof CompleteProfileRoute
  LoginRoute: typeof LoginRoute
  WaitingApprovalRoute: typeof WaitingApprovalRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProfileRoute: typeof ApiProfileRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAttendanceCheckInRoute: typeof ApiAttendanceCheckInRoute
  ApiMembersIdRoute: typeof ApiMembersIdRoute
  ApiMembersImportRoute: typeof ApiMembersImportRoute
  ApiMembersManualRoute: typeof ApiMembersManualRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-disabled': {
      id: '/account-disabled'
      path: '/account-disabled'
      fullPath: '/account-disabled'
      preLoaderRoute: typeof AccountDisabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-approval': {
      id: '/waiting-approval'
      path: '/waiting-approval'
      fullPath: '/waiting-approval'
      preLoaderRoute: typeof WaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/events': {
      id: '/_auth/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthEventsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mahasiswa': {
      id: '/_auth/mahasiswa'
      path: '/mahasiswa'
      fullPath: '/mahasiswa'
      preLoaderRoute: typeof AuthMahasiswaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/members': {
      id: '/_auth/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthMembersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/scan': {
      id: '/_auth/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthScanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/attendance/history': {
      id: '/_auth/attendance/history'
      path: '/attendance/history'
      fullPath: '/attendance/history'
      preLoaderRoute: typeof AuthAttendanceHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/events/$id': {
      id: '/_auth/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof AuthEventsIdRouteImport
      parentRoute: typeof AuthEventsRoute
    }
    '/_auth/events/new': {
      id: '/_auth/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof AuthEventsNewRouteImport
      parentRoute: typeof AuthEventsRoute
    }
    '/api/attendance/check-in': {
      id: '/api/attendance/check-in'
      path: '/api/attendance/check-in'
      fullPath: '/api/attendance/check-in'
      preLoaderRoute: typeof ApiAttendanceCheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/members/$id': {
      id: '/api/members/$id'
      path: '/api/members/$id'
      fullPath: '/api/members/$id'
      preLoaderRoute: typeof ApiMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/import': {
      id: '/api/members/import'
      path: '/api/members/import'
      fullPath: '/api/members/import'
      preLoaderRoute: typeof ApiMembersImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/manual': {
      id: '/api/members/manual'
      path: '/api/members/manual'
      fullPath: '/api/members/manual'
      preLoaderRoute: typeof ApiMembersManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/events/$id/qr': {
      id: '/_auth/events/$id/qr'
      path: '/qr'
      fullPath: '/events/$id/qr'
      preLoaderRoute: typeof AuthEventsIdQrRouteImport
      parentRoute: typeof AuthEventsIdRoute
    }
    '/api/events/$id/session': {
      id: '/api/events/$id/session'
      path: '/session'
      fullPath: '/api/events/$id/session'
      preLoaderRoute: typeof ApiEventsIdSessionRouteImport
      parentRoute: typeof ApiEventsIdRoute
    }
    '/api/events/$id/session/close': {
      id: '/api/events/$id/session/close'
      path: '/close'
      fullPath: '/api/events/$id/session/close'
      preLoaderRoute: typeof ApiEventsIdSessionCloseRouteImport
      parentRoute: typeof ApiEventsIdSessionRoute
    }
    '/api/events/$id/session/open': {
      id: '/api/events/$id/session/open'
      path: '/open'
      fullPath: '/api/events/$id/session/open'
      preLoaderRoute: typeof ApiEventsIdSessionOpenRouteImport
      parentRoute: typeof ApiEventsIdSessionRoute
    }
  }
}

interface AuthEventsIdRouteChildren {
  AuthEventsIdQrRoute: typeof AuthEventsIdQrRoute
}

const AuthEventsIdRouteChildren: AuthEventsIdRouteChildren = {
  AuthEventsIdQrRoute: AuthEventsIdQrRoute,
}

const AuthEventsIdRouteWithChildren = AuthEventsIdRoute._addFileChildren(
  AuthEventsIdRouteChildren,
)

interface AuthEventsRouteChildren {
  AuthEventsIdRoute: typeof AuthEventsIdRouteWithChildren
  AuthEventsNewRoute: typeof AuthEventsNewRoute
}

const AuthEventsRouteChildren: AuthEventsRouteChildren = {
  AuthEventsIdRoute: AuthEventsIdRouteWithChildren,
  AuthEventsNewRoute: AuthEventsNewRoute,
}

const AuthEventsRouteWithChildren = AuthEventsRoute._addFileChildren(
  AuthEventsRouteChildren,
)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEventsRoute: typeof AuthEventsRouteWithChildren
  AuthMahasiswaRoute: typeof AuthMahasiswaRoute
  AuthMembersRoute: typeof AuthMembersRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthScanRoute: typeof AuthScanRoute
  AuthAttendanceHistoryRoute: typeof AuthAttendanceHistoryRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEventsRoute: AuthEventsRouteWithChildren,
  AuthMahasiswaRoute: AuthMahasiswaRoute,
  AuthMembersRoute: AuthMembersRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthScanRoute: AuthScanRoute,
  AuthAttendanceHistoryRoute: AuthAttendanceHistoryRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ApiEventsIdSessionRouteChildren {
  ApiEventsIdSessionCloseRoute: typeof ApiEventsIdSessionCloseRoute
  ApiEventsIdSessionOpenRoute: typeof ApiEventsIdSessionOpenRoute
}

const ApiEventsIdSessionRouteChildren: ApiEventsIdSessionRouteChildren = {
  ApiEventsIdSessionCloseRoute: ApiEventsIdSessionCloseRoute,
  ApiEventsIdSessionOpenRoute: ApiEventsIdSessionOpenRoute,
}

const ApiEventsIdSessionRouteWithChildren =
  ApiEventsIdSessionRoute._addFileChildren(ApiEventsIdSessionRouteChildren)

interface ApiEventsIdRouteChildren {
  ApiEventsIdSessionRoute: typeof ApiEventsIdSessionRouteWithChildren
}

const ApiEventsIdRouteChildren: ApiEventsIdRouteChildren = {
  ApiEventsIdSessionRoute: ApiEventsIdSessionRouteWithChildren,
}

const ApiEventsIdRouteWithChildren = ApiEventsIdRoute._addFileChildren(
  ApiEventsIdRouteChildren,
)

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRouteWithChildren
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRouteWithChildren,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AccountDisabledRoute: AccountDisabledRoute,
  CompleteProfileRoute: CompleteProfileRoute,
  LoginRoute: LoginRoute,
  WaitingApprovalRoute: WaitingApprovalRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiProfileRoute: ApiProfileRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAttendanceCheckInRoute: ApiAttendanceCheckInRoute,
  ApiMembersIdRoute: ApiMembersIdRoute,
  ApiMembersImportRoute: ApiMembersImportRoute,
  ApiMembersManualRoute: ApiMembersManualRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
